// SPDX-License-Identifier: Apache-2.0
// Port of .external/frankentui/crates/ftui-text/src/search.rs.
// Upstream basis: 15cc6543f76b814394c590f9e7719dedd6684e4c.
// Coordinate realization: Rust byte ranges become native .NET UTF-16 ranges;
// normalized matches are mapped back to UTF-16 offsets in the original text.

using System.Globalization;
using System.Text;
using FrankenTui.Core;

namespace FrankenTui.Text;

/// <summary>Unicode character-width policy used for search result columns.</summary>
public enum WidthMode
{
    /// <summary>East Asian Ambiguous scalars occupy one terminal cell.</summary>
    Standard,

    /// <summary>East Asian Ambiguous scalars occupy two terminal cells.</summary>
    CjkAmbiguousWide,
}

/// <summary>Width operations corresponding to the upstream <c>WidthMode</c> methods.</summary>
public static class WidthModeExtensions
{
    // Effective ambiguous ranges generated by unicode-width 0.2.2's Unicode
    // 17.0.0 generator. Zero-width classification still follows the active
    // .NET Unicode database through Rune.GetUnicodeCategory.
    private static readonly (int Start, int End)[] EastAsianAmbiguousRanges =
    [
        (0x00A1, 0x00A1),
        (0x00A4, 0x00A4),
        (0x00A7, 0x00A7),
        (0x00AD, 0x00AE),
        (0x00B0, 0x00B3),
        (0x00B6, 0x00B7),
        (0x00B9, 0x00B9),
        (0x00BC, 0x00BF),
        (0x00D7, 0x00D7),
        (0x00F7, 0x00F7),
        (0x0300, 0x036F),
        (0x0387, 0x0387),
        (0x2010, 0x2010),
        (0x2013, 0x2016),
        (0x2018, 0x2019),
        (0x201C, 0x201D),
        (0x2020, 0x2022),
        (0x2024, 0x2027),
        (0x2030, 0x2030),
        (0x2032, 0x2033),
        (0x2035, 0x2035),
        (0x203B, 0x203B),
        (0x203E, 0x203E),
        (0x2074, 0x2074),
        (0x2081, 0x2084),
        (0x20AC, 0x20AC),
        (0x2103, 0x2103),
        (0x2105, 0x2105),
        (0x2109, 0x2109),
        (0x2116, 0x2116),
        (0x2121, 0x2122),
        (0x2150, 0x215E),
        (0x2160, 0x216B),
        (0x2170, 0x2179),
        (0x2189, 0x2189),
        (0x2190, 0x219B),
        (0x21AE, 0x21AE),
        (0x21B8, 0x21B9),
        (0x21CE, 0x21CF),
        (0x21D2, 0x21D2),
        (0x21D4, 0x21D4),
        (0x21E7, 0x21E7),
        (0x2200, 0x2200),
        (0x2202, 0x2204),
        (0x2207, 0x2209),
        (0x220B, 0x220C),
        (0x220F, 0x220F),
        (0x2211, 0x2211),
        (0x2215, 0x2215),
        (0x221A, 0x221A),
        (0x221D, 0x2220),
        (0x2223, 0x222C),
        (0x222E, 0x222E),
        (0x2234, 0x2237),
        (0x223C, 0x223D),
        (0x2241, 0x2241),
        (0x2248, 0x2249),
        (0x224C, 0x224C),
        (0x2252, 0x2252),
        (0x2260, 0x2262),
        (0x2264, 0x2267),
        (0x226A, 0x226B),
        (0x226E, 0x2271),
        (0x2282, 0x2289),
        (0x2295, 0x2295),
        (0x2299, 0x2299),
        (0x22A5, 0x22A5),
        (0x22BF, 0x22BF),
        (0x2312, 0x2312),
        (0x2460, 0x254B),
        (0x2550, 0x2574),
        (0x2580, 0x258F),
        (0x2592, 0x2595),
        (0x25A0, 0x25A1),
        (0x25A3, 0x25A9),
        (0x25B2, 0x25B3),
        (0x25B6, 0x25B7),
        (0x25BC, 0x25BD),
        (0x25C0, 0x25C1),
        (0x25C6, 0x25C8),
        (0x25CB, 0x25CB),
        (0x25CE, 0x25D1),
        (0x25E2, 0x25E5),
        (0x25EF, 0x25EF),
        (0x2605, 0x2606),
        (0x2609, 0x2609),
        (0x260E, 0x260F),
        (0x2616, 0x2617),
        (0x261C, 0x261C),
        (0x261E, 0x261E),
        (0x2640, 0x2640),
        (0x2642, 0x2642),
        (0x2660, 0x2661),
        (0x2663, 0x2665),
        (0x2667, 0x266A),
        (0x266C, 0x266D),
        (0x266F, 0x266F),
        (0x269E, 0x269F),
        (0x26BF, 0x26BF),
        (0x26C6, 0x26CD),
        (0x26CF, 0x26D3),
        (0x26D5, 0x26E1),
        (0x26E3, 0x26E3),
        (0x26E8, 0x26E9),
        (0x26EB, 0x26F1),
        (0x26F4, 0x26F4),
        (0x26F6, 0x26F9),
        (0x26FB, 0x26FC),
        (0x26FE, 0x26FF),
        (0x273D, 0x273D),
        (0x2757, 0x2757),
        (0x2776, 0x2793),
        (0x2B55, 0x2B59),
        (0x3248, 0x324F),
        (0xE000, 0xF8FF),
        (0xFE00, 0xFE0F),
        (0xFFFD, 0xFFFD),
        (0x1F100, 0x1F10C),
        (0x1F110, 0x1F12D),
        (0x1F130, 0x1F169),
        (0x1F170, 0x1F1AC),
        (0xE0100, 0xE01EF),
        (0xF0000, 0xFFFFD),
        (0x100000, 0x10FFFD),
    ];

    /// <summary>Returns the terminal-cell width of one Unicode scalar.</summary>
    public static int CharWidth(this WidthMode mode, Rune value)
    {
        ValidateMode(mode);

        // unicode-width 0.2.2 scalar exceptions that are not expressible by
        // the BCL general category or the shared terminal-wide ranges.
        if (value.Value == 0x2D7F)
        {
            return 1;
        }

        if (value.Value is 0x115F or 0x17A4 or 0x17D8)
        {
            return 2;
        }

        if (value.Value is >= 0x1F1E6 and <= 0x1F1FF)
        {
            return 1;
        }

        var category = Rune.GetUnicodeCategory(value);
        if (category is UnicodeCategory.Control
            or UnicodeCategory.NonSpacingMark
            or UnicodeCategory.EnclosingMark
            or UnicodeCategory.Format)
        {
            return 0;
        }

        var width = Math.Min(TerminalTextWidth.RuneWidth(value), 2);
        return width == 1
            && mode == WidthMode.CjkAmbiguousWide
            && IsEastAsianAmbiguous(value.Value)
                ? 2
                : width;
    }

    /// <summary>Convenience overload for a BMP scalar.</summary>
    public static int CharWidth(this WidthMode mode, char value)
    {
        if (!Rune.TryCreate(value, out var rune))
        {
            throw new ArgumentException("A UTF-16 surrogate is not a complete Unicode scalar.", nameof(value));
        }

        return mode.CharWidth(rune);
    }

    /// <summary>Returns the summed per-scalar display width of <paramref name="text"/>.</summary>
    public static int StrWidth(this WidthMode mode, string text)
    {
        ArgumentNullException.ThrowIfNull(text);
        ValidateMode(mode);
        TextSearch.ValidateUtf16(text, nameof(text));

        var width = 0;
        foreach (var rune in text.EnumerateRunes())
        {
            width += mode.CharWidth(rune);
        }

        return width;
    }

    internal static void ValidateMode(WidthMode mode)
    {
        if (mode is not WidthMode.Standard and not WidthMode.CjkAmbiguousWide)
        {
            throw new ArgumentOutOfRangeException(nameof(mode), mode, "Unknown search width mode.");
        }
    }

    private static bool IsEastAsianAmbiguous(int scalar)
    {
        var low = 0;
        var high = EastAsianAmbiguousRanges.Length - 1;
        while (low <= high)
        {
            var middle = low + ((high - low) / 2);
            var range = EastAsianAmbiguousRanges[middle];
            if (scalar < range.Start)
            {
                high = middle - 1;
            }
            else if (scalar > range.End)
            {
                low = middle + 1;
            }
            else
            {
                return true;
            }
        }

        return false;
    }
}

/// <summary>
/// A search match in native .NET UTF-16 coordinates. The upstream Rust range
/// stores UTF-8 byte offsets; both representations point at the same scalars.
/// </summary>
public readonly record struct SearchResult(int Start, int End)
{
    /// <summary>Returns the match as a native .NET range.</summary>
    public Range Range => Start..End;

    /// <summary>Named constructor corresponding to the upstream <c>new</c>.</summary>
    public static SearchResult New(int start, int end) => new(start, end);

    /// <summary>Extracts the matched text from its source.</summary>
    public string Text(string source) => TextSearch.ExtractRange(source, Start, End);
}

/// <summary>Normalization, case, and terminal-width policy for Unicode search.</summary>
public readonly record struct SearchPolicy(
    NormalizationForm NormForm,
    bool CaseInsensitive,
    WidthMode WidthMode)
{
    /// <summary>NFKC, case-insensitive, standard-width search.</summary>
    public static SearchPolicy Standard { get; } =
        new(NormalizationForm.FormKC, true, global::FrankenTui.Text.WidthMode.Standard);

    /// <summary>NFKC, case-insensitive, CJK ambiguous-wide search.</summary>
    public static SearchPolicy Cjk { get; } =
        new(NormalizationForm.FormKC, true, global::FrankenTui.Text.WidthMode.CjkAmbiguousWide);

    /// <summary>NFC, case-sensitive, standard-width search.</summary>
    public static SearchPolicy ExactNfc { get; } =
        new(NormalizationForm.FormC, false, global::FrankenTui.Text.WidthMode.Standard);
}

/// <summary>A source range enriched with terminal display-column coordinates.</summary>
public readonly record struct PolicySearchResult(
    int Start,
    int End,
    int ColumnStart,
    int ColumnEnd)
{
    /// <summary>Returns the match as a native .NET range.</summary>
    public Range Range => Start..End;

    /// <summary>Extracts the matched text from its source.</summary>
    public string Text(string source) => TextSearch.ExtractRange(source, Start, End);

    /// <summary>Returns the terminal display width of the match.</summary>
    public int DisplayWidth() => ColumnEnd - ColumnStart;
}

/// <summary>Unicode-aware exact, normalized, case-insensitive, and policy search.</summary>
public static class TextSearch
{
    /// <summary>
    /// Computes the display column at a UTF-16 scalar boundary. This is the
    /// native-coordinate counterpart of upstream <c>display_col_at</c>.
    /// </summary>
    public static int DisplayColumnAt(string text, int utf16Offset, WidthMode mode)
    {
        ArgumentNullException.ThrowIfNull(text);
        ValidateUtf16(text, nameof(text));
        WidthModeExtensions.ValidateMode(mode);
        ValidateRange(text, utf16Offset, utf16Offset);

        var width = 0;
        foreach (var rune in text.AsSpan(0, utf16Offset).EnumerateRunes())
        {
            width += mode.CharWidth(rune);
        }

        return width;
    }

    /// <summary>Finds non-overlapping ordinal matches in one string.</summary>
    public static IReadOnlyList<SearchResult> SearchExact(string haystack, string needle)
    {
        ValidateSearchInputs(haystack, needle);
        if (needle.Length == 0)
        {
            return [];
        }

        var results = new List<SearchResult>();
        var start = 0;
        while (start <= haystack.Length)
        {
            var found = haystack.IndexOf(needle, start, StringComparison.Ordinal);
            if (found < 0)
            {
                break;
            }

            results.Add(SearchResult.New(found, found + needle.Length));
            start = found + needle.Length;
        }

        return results;
    }

    /// <summary>Finds ordinal matches, advancing by one Unicode scalar after each start.</summary>
    public static IReadOnlyList<SearchResult> SearchExactOverlapping(string haystack, string needle)
    {
        ValidateSearchInputs(haystack, needle);
        if (needle.Length == 0)
        {
            return [];
        }

        var results = new List<SearchResult>();
        var start = 0;
        while (start <= haystack.Length)
        {
            var found = haystack.IndexOf(needle, start, StringComparison.Ordinal);
            if (found < 0)
            {
                break;
            }

            results.Add(SearchResult.New(found, found + needle.Length));
            start = AdvanceScalar(haystack, found);
        }

        return results;
    }

    /// <summary>Finds non-overlapping matches after lowering ASCII A-Z only.</summary>
    public static IReadOnlyList<SearchResult> SearchAsciiCaseInsensitive(string haystack, string needle)
    {
        ValidateSearchInputs(haystack, needle);
        if (needle.Length == 0)
        {
            return [];
        }

        var loweredHaystack = LowerAscii(haystack);
        var loweredNeedle = LowerAscii(needle);
        var results = new List<SearchResult>();
        var start = 0;
        while (start <= loweredHaystack.Length)
        {
            var found = loweredHaystack.IndexOf(loweredNeedle, start, StringComparison.Ordinal);
            if (found < 0)
            {
                break;
            }

            results.Add(SearchResult.New(found, found + needle.Length));
            start = found + needle.Length;
        }

        return results;
    }

    /// <summary>Finds NFKC plus invariant-lowercase matches in original coordinates.</summary>
    public static IReadOnlyList<SearchResult> SearchCaseInsensitive(string haystack, string needle) =>
        SearchMapped(haystack, needle, TextNormalizer.NormalizeForSearch, StringComparison.Ordinal);

    /// <summary>Finds normalization-equivalent matches in original coordinates.</summary>
    public static IReadOnlyList<SearchResult> SearchNormalized(
        string haystack,
        string needle,
        NormalizationForm form) =>
        SearchMapped(
            haystack,
            needle,
            text => TextNormalizer.Normalize(text, form),
            StringComparison.Ordinal);

    /// <summary>Searches with explicit normalization, case, and width policy.</summary>
    public static IReadOnlyList<PolicySearchResult> SearchWithPolicy(
        string haystack,
        string needle,
        SearchPolicy policy)
    {
        WidthModeExtensions.ValidateMode(policy.WidthMode);

        string Transform(string text)
        {
            var normalized = TextNormalizer.Normalize(text, policy.NormForm);
            return policy.CaseInsensitive ? normalized.ToLowerInvariant() : normalized;
        }

        var matches = SearchMapped(haystack, needle, Transform, StringComparison.Ordinal);
        if (matches.Count == 0)
        {
            return [];
        }

        var results = new List<PolicySearchResult>(matches.Count);
        foreach (var match in matches)
        {
            results.Add(new PolicySearchResult(
                match.Start,
                match.End,
                DisplayColumnAt(haystack, match.Start, policy.WidthMode),
                DisplayColumnAt(haystack, match.End, policy.WidthMode)));
        }

        return results;
    }

    /// <summary>
    /// Compatibility projection over a line-oriented <see cref="TextDocument"/>.
    /// Columns retain their historical native UTF-16 meaning.
    /// </summary>
    public static IReadOnlyList<TextCursor> FindAll(
        TextDocument document,
        string needle,
        StringComparison comparison = StringComparison.OrdinalIgnoreCase)
    {
        ArgumentNullException.ThrowIfNull(document);
        ArgumentNullException.ThrowIfNull(needle);
        if (needle.Length == 0)
        {
            return [];
        }

        var result = new List<TextCursor>();
        for (var lineIndex = 0; lineIndex < document.Lines.Count; lineIndex++)
        {
            var line = document.Lines[lineIndex].PlainText;
            var offset = 0;
            while (offset <= line.Length)
            {
                var found = line.IndexOf(needle, offset, comparison);
                if (found < 0)
                {
                    break;
                }

                result.Add(new TextCursor(lineIndex, found));
                offset = found + needle.Length;
            }
        }

        return result;
    }

    /// <summary>
    /// Compatibility projection that normalizes each line, then maps every
    /// result back to the original line's UTF-16 coordinate space.
    /// </summary>
    public static IReadOnlyList<TextCursor> FindAllNormalized(
        TextDocument document,
        string needle,
        NormalizationForm normalization = NormalizationForm.FormKC,
        StringComparison comparison = StringComparison.OrdinalIgnoreCase)
    {
        ArgumentNullException.ThrowIfNull(document);
        ArgumentNullException.ThrowIfNull(needle);

        var result = new List<TextCursor>();
        for (var lineIndex = 0; lineIndex < document.Lines.Count; lineIndex++)
        {
            var line = document.Lines[lineIndex].PlainText;
            var matches = SearchMapped(
                line,
                needle,
                text => TextNormalizer.Normalize(text, normalization),
                comparison);
            foreach (var match in matches)
            {
                result.Add(new TextCursor(lineIndex, match.Start));
            }
        }

        return result;
    }

    internal static string ExtractRange(string source, int start, int end)
    {
        ArgumentNullException.ThrowIfNull(source);
        ValidateUtf16(source, nameof(source));
        ValidateRange(source, start, end);
        return source[start..end];
    }

    internal static void ValidateUtf16(string text, string parameterName)
    {
        for (var index = 0; index < text.Length; index++)
        {
            var value = text[index];
            if (char.IsHighSurrogate(value))
            {
                if (index + 1 >= text.Length || !char.IsLowSurrogate(text[index + 1]))
                {
                    throw new ArgumentException("Text contains malformed UTF-16.", parameterName);
                }

                index++;
            }
            else if (char.IsLowSurrogate(value))
            {
                throw new ArgumentException("Text contains malformed UTF-16.", parameterName);
            }
        }
    }

    private static IReadOnlyList<SearchResult> SearchMapped(
        string haystack,
        string needle,
        Func<string, string> transform,
        StringComparison comparison)
    {
        ValidateSearchInputs(haystack, needle);
        ArgumentNullException.ThrowIfNull(transform);
        if (needle.Length == 0)
        {
            return [];
        }

        var normalizedNeedle = transform(needle);
        ValidateUtf16(normalizedNeedle, nameof(needle));
        if (normalizedNeedle.Length == 0)
        {
            return [];
        }

        var mapped = BuildMappedText(haystack, transform);
        if (mapped.Text.Length == 0)
        {
            return [];
        }

        var results = new List<SearchResult>();
        var start = 0;
        while (start <= mapped.Text.Length)
        {
            var found = mapped.Text.IndexOf(normalizedNeedle, start, comparison);
            if (found < 0)
            {
                break;
            }

            var normalizedEnd = found + normalizedNeedle.Length;
            var mappedEnd = Math.Min(normalizedEnd, mapped.Text.Length);
            var originalStart = found < mapped.OriginalStarts.Length
                ? mapped.OriginalStarts[found]
                : haystack.Length;
            var originalEnd = mappedEnd > 0
                ? mapped.OriginalEnds[mappedEnd - 1]
                : originalStart;
            var match = SearchResult.New(originalStart, originalEnd);

            if (results.Count == 0 || results[^1] != match)
            {
                results.Add(match);
            }

            start = normalizedEnd;
        }

        return results;
    }

    private static MappedText BuildMappedText(string source, Func<string, string> transform)
    {
        var text = new StringBuilder(source.Length);
        var originalStarts = new List<int>(source.Length);
        var originalEnds = new List<int>(source.Length);
        var elements = StringInfo.GetTextElementEnumerator(source);
        while (elements.MoveNext())
        {
            var originalStart = elements.ElementIndex;
            var element = elements.GetTextElement();
            var originalEnd = originalStart + element.Length;
            var chunk = transform(element);
            ValidateUtf16(chunk, nameof(source));
            if (chunk.Length == 0)
            {
                continue;
            }

            text.Append(chunk);
            for (var index = 0; index < chunk.Length; index++)
            {
                originalStarts.Add(originalStart);
                originalEnds.Add(originalEnd);
            }
        }

        return new MappedText(text.ToString(), [.. originalStarts], [.. originalEnds]);
    }

    private static string LowerAscii(string text) =>
        string.Create(text.Length, text, static (destination, source) =>
        {
            for (var index = 0; index < source.Length; index++)
            {
                var value = source[index];
                destination[index] = value is >= 'A' and <= 'Z'
                    ? (char)(value + ('a' - 'A'))
                    : value;
            }
        });

    private static int AdvanceScalar(string text, int utf16Offset)
    {
        var value = text[utf16Offset];
        return utf16Offset + (char.IsHighSurrogate(value) ? 2 : 1);
    }

    private static void ValidateSearchInputs(string haystack, string needle)
    {
        ArgumentNullException.ThrowIfNull(haystack);
        ArgumentNullException.ThrowIfNull(needle);
        ValidateUtf16(haystack, nameof(haystack));
        ValidateUtf16(needle, nameof(needle));
    }

    private static void ValidateRange(string source, int start, int end)
    {
        if (start < 0 || end < start || end > source.Length)
        {
            throw new ArgumentOutOfRangeException(nameof(start), "Range must be ordered and within the source.");
        }

        if (!IsScalarBoundary(source, start) || !IsScalarBoundary(source, end))
        {
            throw new ArgumentException("Range endpoints must be UTF-16 scalar boundaries.", nameof(start));
        }
    }

    private static bool IsScalarBoundary(string text, int offset) =>
        offset == 0
        || offset == text.Length
        || !(char.IsHighSurrogate(text[offset - 1]) && char.IsLowSurrogate(text[offset]));

    private readonly record struct MappedText(
        string Text,
        int[] OriginalStarts,
        int[] OriginalEnds);
}
