namespace FrankenTui.Runtime;

public sealed record RuntimeFrameStats(
    int StepIndex,
    int ChangedCells,
    int RunCount,
    int BytesEmitted,
    double FrameDurationMs,
    double PresentDurationMs,
    double DiffDurationMs,
    int DirtyRows,
    string DegradationLevel,
    bool SyncOutput,
    bool Truncated,
    int QueueLength = 0,
    string LoadGovernorAction = "stay",
    string LoadGovernorReason = "initial",
    double LoadGovernorPidOutput = 0,
    double LoadGovernorPidP = 0,
    double LoadGovernorPidI = 0,
    double LoadGovernorPidD = 0,
    double LoadGovernorEProcessValue = 1,
    double LoadGovernorEProcessSigmaMs = 1,
    uint LoadGovernorFramesObserved = 0,
    int LoadGovernorFramesSinceChange = 0,
    double LoadGovernorPidGateThreshold = 0,
    double LoadGovernorPidGateMargin = 0,
    double LoadGovernorEvidenceThreshold = 0,
    double LoadGovernorEvidenceMargin = 0,
    bool LoadGovernorEProcessInWarmup = true,
    ulong LoadGovernorTransitionSeq = 0,
    ulong LoadGovernorTransitionCorrelationId = 0,
    string CascadeDecision = "hold",
    string CascadeLevelBefore = "FULL",
    string CascadeLevelAfter = "FULL",
    string CascadeGuardState = "warmup",
    string ConformalBucketKey = "altscreen:full:10",
    double ConformalUpperMicroseconds = 0,
    double ConformalBudgetMicroseconds = 0,
    int ConformalCalibrationSize = 0,
    byte ConformalFallbackLevel = 0,
    double ConformalIntervalWidthMicroseconds = 0,
    int CascadeRecoveryStreak = 0,
    int CascadeRecoveryThreshold = 10)
{
    public static RuntimeFrameStats Empty { get; } = new(
        StepIndex: 0,
        ChangedCells: 0,
        RunCount: 0,
        BytesEmitted: 0,
        FrameDurationMs: 0,
        PresentDurationMs: 0,
        DiffDurationMs: 0,
        DirtyRows: 0,
        DegradationLevel: "FULL",
        SyncOutput: false,
        Truncated: false);
}
