// Tests for .external/frankentui/crates/ftui-runtime/src/validation_pipeline.rs
using FrankenTui.Runtime;

namespace FrankenTui.Tests.Headless;

public class ValidationPipelineTests
{
    static PipelineConfig Cfg(double? ga=null,double? gb=null,double? gamma=null,TimeSpan? cmin=null){var c=PipelineConfig.Default;if(ga.HasValue)c.PriorAlpha=ga.Value;if(gb.HasValue)c.PriorBeta=gb.Value;if(gamma.HasValue)c.Gamma=gamma.Value;if(cmin.HasValue)c.CMin=cmin.Value;return c;}

    [Fact] public void EmptyPipelineReturnsSuccess(){var p=new ValidationPipeline();var r=p.Run(_=>throw new Exception("unreachable"));Assert.True(r.AllPassed);Assert.Empty(r.Outcomes);Assert.Equal(TimeSpan.Zero,r.TotalCost);Assert.Equal(0,r.Skipped);}
    [Fact] public void SingleValidatorPass(){var p=new ValidationPipeline();p.Register("a",TimeSpan.FromMilliseconds(10));var r=p.Run(_=>(true,TimeSpan.FromMilliseconds(8)));Assert.True(r.AllPassed);Assert.Single(r.Outcomes);}
    [Fact] public void SingleValidatorFail(){var p=new ValidationPipeline();p.Register("a",TimeSpan.FromMilliseconds(10));var r=p.Run(_=>(false,TimeSpan.FromMilliseconds(5)));Assert.False(r.AllPassed);Assert.Single(r.Outcomes);}
    [Fact] public void EarlyExitOnFailure(){var p=new ValidationPipeline();p.Register("f",TimeSpan.FromMilliseconds(1));p.Register("e",TimeSpan.FromMilliseconds(100));p.Register("e2",TimeSpan.FromMilliseconds(50));for(int i=0;i<10;i++)p.Update(new(0,false,TimeSpan.FromMilliseconds(1)));var ran=new List<int>();var r=p.Run(id=>{ran.Add(id);return id==0?(false,TimeSpan.FromMilliseconds(1)):(true,TimeSpan.FromMilliseconds(50));});Assert.False(r.AllPassed);Assert.Single(ran);Assert.Equal(0,ran[0]);Assert.Equal(2,r.Skipped);}
    [Fact] public void OptimalOrderingSortsByScore(){var p=new ValidationPipeline();var a=p.Register("a",TimeSpan.FromMilliseconds(1));var b=p.Register("b",TimeSpan.FromMilliseconds(100));var c=p.Register("c",TimeSpan.FromMilliseconds(1));for(int i=0;i<8;i++)p.Update(new(b,false,TimeSpan.FromMilliseconds(100)));for(int i=0;i<8;i++)p.Update(new(c,false,TimeSpan.FromMilliseconds(1)));for(int i=0;i<8;i++)p.Update(new(a,true,TimeSpan.FromMilliseconds(1)));var(ordering,_)=p.ComputeOrdering();Assert.Equal(c,ordering[0]);Assert.Equal(a,ordering[1]);Assert.Equal(b,ordering[2]);}
    [Fact] public void ExpectedCostFormula(){var p=new ValidationPipeline();var a=p.Register("A",TimeSpan.FromMilliseconds(10));var b=p.Register("B",TimeSpan.FromMilliseconds(100));for(int i=0;i<7;i++)p.Update(new(a,false,TimeSpan.FromMilliseconds(10)));p.Update(new(a,true,TimeSpan.FromMilliseconds(10)));p.Update(new(b,false,TimeSpan.FromMilliseconds(100)));for(int i=0;i<7;i++)p.Update(new(b,true,TimeSpan.FromMilliseconds(100)));double pa=p.Stats(a)!.FailureProb,pb=p.Stats(b)!.FailureProb;Assert.InRange(pa,0.79,0.81);Assert.InRange(pb,0.19,0.21);Assert.True(p.ExpectedCost(new List<int>{a,b})<p.ExpectedCost(new List<int>{b,a}));}
    [Fact] public void PosteriorUpdate(){var p=new ValidationPipeline();var id=p.Register("v",TimeSpan.FromMilliseconds(5));Assert.InRange(p.Stats(id)!.FailureProb,0.49,0.51);for(int i=0;i<3;i++)p.Update(new(id,false,TimeSpan.FromMilliseconds(5)));Assert.InRange(p.Stats(id)!.FailureProb,0.79,0.81);for(int i=0;i<4;i++)p.Update(new(id,true,TimeSpan.FromMilliseconds(5)));Assert.InRange(p.Stats(id)!.FailureProb,4.0/9-0.01,4.0/9+0.01);}
    [Fact] public void CostEmaUpdates(){var p=new ValidationPipeline(Cfg(gamma:0.5));var id=p.Register("v",TimeSpan.FromMilliseconds(10));p.Update(new(id,true,TimeSpan.FromMilliseconds(20)));Assert.InRange(p.Stats(id)!.CostEma.TotalMilliseconds,14.9,15.1);p.Update(new(id,true,TimeSpan.FromMilliseconds(30)));Assert.InRange(p.Stats(id)!.CostEma.TotalMilliseconds,22.4,22.6);}
    [Fact] public void CostFloorPreventsZero(){var p=new ValidationPipeline();var id=p.Register("v",TimeSpan.Zero);Assert.True(p.Stats(id)!.CostEma>=TimeSpan.FromTicks(10));}
    [Fact] public void LedgerRecordsAll(){var p=new ValidationPipeline();p.Register("a",TimeSpan.FromMilliseconds(5));p.Register("b",TimeSpan.FromMilliseconds(10));p.Register("c",TimeSpan.FromMilliseconds(15));var(_,l)=p.ComputeOrdering();Assert.Equal(3,l.Count);Assert.Equal(new[]{0,1,2},l.Select(e=>e.Rank).OrderBy(x=>x));}
    [Fact] public void Deterministic(){var run=()=>{var p=new ValidationPipeline();p.Register("x",TimeSpan.FromMilliseconds(10));p.Register("y",TimeSpan.FromMilliseconds(20));p.Register("z",TimeSpan.FromMilliseconds(5));foreach(var(id,passed,ms)in new[]{ (0,false,10),(1,true,20),(2,false,5),(0,true,12),(1,false,18),(2,true,6),(0,false,9),(1,true,22),(2,false,4)})p.Update(new(id,passed,TimeSpan.FromMilliseconds(ms)));var(o,_)=p.ComputeOrdering();return(o,p.ExpectedCost(o));};var(o1,c1)=run();var(o2,c2)=run();Assert.Equal(o1,o2);Assert.InRange(c1-c2,-1e-15,1e-15);}
    [Fact] public void SummaryShowsImprovement(){var p=new ValidationPipeline();p.Register("e",TimeSpan.FromMilliseconds(100));p.Register("c",TimeSpan.FromMilliseconds(1));for(int i=0;i<20;i++)p.Update(new(1,false,TimeSpan.FromMilliseconds(1)));for(int i=0;i<20;i++)p.Update(new(0,true,TimeSpan.FromMilliseconds(100)));var s=p.Summary();Assert.Equal(1,s.OptimalOrdering[0]);Assert.True(s.ImprovementFraction>0);}
    [Fact] public void VarianceDecreases(){var p=new ValidationPipeline();var id=p.Register("v",TimeSpan.FromMilliseconds(5));var v0=p.Stats(id)!.Variance;for(int i=0;i<10;i++)p.Update(new(id,false,TimeSpan.FromMilliseconds(5)));var v10=p.Stats(id)!.Variance;for(int i=0;i<90;i++)p.Update(new(id,false,TimeSpan.FromMilliseconds(5)));Assert.True(v10<v0);Assert.True(p.Stats(id)!.Variance<v10);}
    [Fact] public void ConfidenceWidthContracts(){var p=new ValidationPipeline();var id=p.Register("v",TimeSpan.FromMilliseconds(5));var w0=p.Stats(id)!.ConfidenceWidth;for(int i=0;i<50;i++)p.Update(new(id,true,TimeSpan.FromMilliseconds(5)));Assert.True(p.Stats(id)!.ConfidenceWidth<w0);}
    [Fact] public void UpdateBatchIncrementsRuns(){var p=new ValidationPipeline();p.Register("v",TimeSpan.FromMilliseconds(5));Assert.Equal(0UL,p.TotalRuns);p.UpdateBatch(new(true,new List<ValidationOutcome>{new(0,true,TimeSpan.FromMilliseconds(4))},TimeSpan.FromMilliseconds(4),new List<int>{0},new List<LedgerEntry>(),0));Assert.Equal(1UL,p.TotalRuns);}
    [Fact] public void StatsInvalidIdReturnsNull(){var p=new ValidationPipeline();Assert.Null(p.Stats(0));Assert.Null(p.Stats(999));}
    [Fact] public void UpdateInvalidIdIsNoop(){var p=new ValidationPipeline();p.Register("v",TimeSpan.FromMilliseconds(5));p.Update(new(99,false,TimeSpan.FromMilliseconds(5)));Assert.Equal(0UL,p.Stats(0)!.Observations);}
    [Fact] public void TieBreakById(){var p=new ValidationPipeline();p.Register("second",TimeSpan.FromMilliseconds(10));p.Register("first",TimeSpan.FromMilliseconds(10));Assert.Equal(new List<int>{0,1},p.ComputeOrdering().ordering);}
    [Fact] public void OrderingReversesAfterLearning(){var p=new ValidationPipeline();var a=p.Register("a",TimeSpan.FromMilliseconds(10));var b=p.Register("b",TimeSpan.FromMilliseconds(10));Assert.Equal(new List<int>{0,1},p.ComputeOrdering().ordering);for(int i=0;i<20;i++){p.Update(new(b,false,TimeSpan.FromMilliseconds(10)));p.Update(new(a,true,TimeSpan.FromMilliseconds(10)));}Assert.Equal(1,p.ComputeOrdering().ordering[0]);}
    [Fact] public void StrongPriorDominates(){var p=new ValidationPipeline(Cfg(ga:100,gb:100));var id=p.Register("v",TimeSpan.FromMilliseconds(5));for(int i=0;i<5;i++)p.Update(new(id,false,TimeSpan.FromMilliseconds(5)));Assert.InRange(p.Stats(id)!.FailureProb,105.0/205-0.01,105.0/205+0.01);}
    [Fact] public void MultiplePipelinesIndependent(){var p1=new ValidationPipeline();var p2=new ValidationPipeline();p1.Register("v",TimeSpan.FromMilliseconds(5));p2.Register("v",TimeSpan.FromMilliseconds(5));for(int i=0;i<10;i++)p1.Update(new(0,false,TimeSpan.FromMilliseconds(5)));Assert.Equal(0UL,p2.Stats(0)!.Observations);Assert.Equal(10UL,p1.Stats(0)!.Observations);}
    [Fact] public void LedgerScoresDescending(){var p=new ValidationPipeline();p.Register("a",TimeSpan.FromMilliseconds(5));p.Register("b",TimeSpan.FromMilliseconds(50));p.Register("c",TimeSpan.FromMilliseconds(1));var(_,l)=p.ComputeOrdering();for(int i=0;i<l.Count-1;i++)Assert.True(l[i].Score>=l[i+1].Score);}
    [Fact] public void ExpectedCostManyValidators(){var p=new ValidationPipeline();for(int i=0;i<10;i++)p.Register($"v{i}",TimeSpan.FromMilliseconds(10));var ord=Enumerable.Range(0,10).ToList();double c=0.010,expected=c*Enumerable.Range(0,10).Select(k=>Math.Pow(0.5,k)).Sum();Assert.InRange(p.ExpectedCost(ord)-expected,-1e-10,1e-10);}
    [Fact] public void ObservationsAndFailuresCounters(){var p=new ValidationPipeline();var id=p.Register("v",TimeSpan.FromMilliseconds(5));Assert.Equal(0UL,p.Stats(id)!.Observations);Assert.Equal(0UL,p.Stats(id)!.Failures);for(int i=0;i<3;i++)p.Update(new(id,false,TimeSpan.FromMilliseconds(5)));Assert.Equal(3UL,p.Stats(id)!.Observations);Assert.Equal(3UL,p.Stats(id)!.Failures);}
    [Fact] public void RunAllPassMultiValidator(){var p=new ValidationPipeline();p.Register("a",TimeSpan.FromMilliseconds(5));p.Register("b",TimeSpan.FromMilliseconds(10));p.Register("c",TimeSpan.FromMilliseconds(15));var r=p.Run(_=>(true,TimeSpan.FromMilliseconds(7)));Assert.True(r.AllPassed);Assert.Equal(3,r.Outcomes.Count);}
    [Fact] public void RunFailureAtSecond(){var p=new ValidationPipeline();p.Register("a",TimeSpan.FromMilliseconds(5));p.Register("b",TimeSpan.FromMilliseconds(10));p.Register("c",TimeSpan.FromMilliseconds(15));var r=p.Run(id=>id==1?(false,TimeSpan.FromMilliseconds(10)):(true,TimeSpan.FromMilliseconds(5)));Assert.False(r.AllPassed);Assert.Equal(2,r.Outcomes.Count);Assert.Equal(1,r.Skipped);}
    [Fact] public void EmaGammaOne(){var p=new ValidationPipeline(Cfg(gamma:1));var id=p.Register("v",TimeSpan.FromMilliseconds(100));p.Update(new(id,true,TimeSpan.FromMilliseconds(50)));Assert.Equal(50,p.Stats(id)!.CostEma.TotalMilliseconds,0);}
    [Fact] public void RunThenUpdateBatchRoundTrip(){var p=new ValidationPipeline();p.Register("fast",TimeSpan.FromMilliseconds(1));p.Register("slow",TimeSpan.FromMilliseconds(100));var r=p.Run(id=>id==0?(true,TimeSpan.FromMilliseconds(2)):(true,TimeSpan.FromMilliseconds(80)));p.UpdateBatch(r);Assert.Equal(1UL,p.TotalRuns);Assert.Equal(1UL,p.Stats(0)!.Observations);Assert.Equal(1UL,p.Stats(1)!.Observations);}
    [Fact] public void PipelineResultTotalCostAccumulates(){var p=new ValidationPipeline();p.Register("a",TimeSpan.FromMilliseconds(5));p.Register("b",TimeSpan.FromMilliseconds(10));var r=p.Run(id=>id==0?(true,TimeSpan.FromMilliseconds(7)):(true,TimeSpan.FromMilliseconds(12)));Assert.Equal(TimeSpan.FromMilliseconds(19),r.TotalCost);}

    // ── Additional tests ──
    [Fact] public void ZeroPriorDefaultsToUniform(){var p=new ValidationPipeline(Cfg(ga:0,gb:0));p.Register("a",TimeSpan.FromMilliseconds(10));p.Register("b",TimeSpan.FromMilliseconds(20));var(_,l)=p.ComputeOrdering();Assert.Equal(2,l.Count);foreach(var e in l)Assert.InRange(e.P,0.49,0.51);}
    [Fact] public void CostEmaGammaOneFullReplacement(){var p=new ValidationPipeline(Cfg(gamma:1));var id=p.Register("v",TimeSpan.FromMilliseconds(100));p.Update(new(id,true,TimeSpan.FromMilliseconds(50)));Assert.Equal(50,p.Stats(id)!.CostEma.TotalMilliseconds,0);}
    [Fact] public void CostEmaGammaNearZeroMinimal(){var p=new ValidationPipeline(Cfg(gamma:0.01));var id=p.Register("v",TimeSpan.FromMilliseconds(100));p.Update(new(id,true,TimeSpan.FromMilliseconds(200)));var cost=p.Stats(id)!.CostEma.TotalMilliseconds;Assert.True(cost>=100&&cost<=102,$"cost={cost}");}
    [Fact] public void CostEmaFloorDuringUpdate(){var p=new ValidationPipeline();var id=p.Register("v",TimeSpan.FromMilliseconds(10));p.Update(new(id,true,TimeSpan.Zero));Assert.True(p.Stats(id)!.CostEma>=TimeSpan.FromTicks(10));}
    [Fact] public void TieBreakThreeWay(){var p=new ValidationPipeline();p.Register("c",TimeSpan.FromMilliseconds(5));p.Register("a",TimeSpan.FromMilliseconds(5));p.Register("b",TimeSpan.FromMilliseconds(5));Assert.Equal(new List<int>{0,1,2},p.ComputeOrdering().ordering);}
    [Fact] public void ExpectedCostSingleValidator(){var p=new ValidationPipeline();p.Register("v",TimeSpan.FromMilliseconds(10));var c=p.ExpectedCost(new List<int>{0});Assert.InRange(c-p.Stats(0)!.CostEma.TotalSeconds,-1e-12,1e-12);}
    [Fact] public void ExpectedCostEmptyOrdering(){var p=new ValidationPipeline();p.Register("v",TimeSpan.FromMilliseconds(10));Assert.InRange(p.ExpectedCost(new List<int>()),-1e-15,1e-15);}
    [Fact] public void SummarySingleValidator(){var p=new ValidationPipeline();p.Register("v",TimeSpan.FromMilliseconds(10));var s=p.Summary();Assert.Equal(1,s.ValidatorCount);Assert.Equal(new List<int>{0},s.OptimalOrdering);Assert.InRange(s.ImprovementFraction,-1e-10,1e-10);}
    [Fact] public void SummaryIdenticalValidatorsNoImprovement(){var p=new ValidationPipeline();p.Register("a",TimeSpan.FromMilliseconds(10));p.Register("b",TimeSpan.FromMilliseconds(10));Assert.InRange(p.Summary().ImprovementFraction,-1e-10,1e-10);}
    [Fact] public void RunAllPassMultiValidatorCheck(){var p=new ValidationPipeline();p.Register("a",TimeSpan.FromMilliseconds(5));p.Register("b",TimeSpan.FromMilliseconds(10));p.Register("c",TimeSpan.FromMilliseconds(15));var r=p.Run(_=>(true,TimeSpan.FromMilliseconds(7)));Assert.True(r.AllPassed);Assert.Equal(3,r.Outcomes.Count);Assert.Equal(0,r.Skipped);}
    [Fact] public void RunFailureAtSecondPosition(){var p=new ValidationPipeline();p.Register("a",TimeSpan.FromMilliseconds(5));p.Register("b",TimeSpan.FromMilliseconds(10));p.Register("c",TimeSpan.FromMilliseconds(15));var r=p.Run(id=>id==1?(false,TimeSpan.FromMilliseconds(10)):(true,TimeSpan.FromMilliseconds(5)));Assert.False(r.AllPassed);Assert.Equal(2,r.Outcomes.Count);Assert.Equal(1,r.Skipped);}
    [Fact] public void UpdateBatchMultipleCallsIncrementRuns(){var p=new ValidationPipeline();p.Register("v",TimeSpan.FromMilliseconds(5));var r=new PipelineResult(true,new List<ValidationOutcome>{new(0,true,TimeSpan.FromMilliseconds(4))},TimeSpan.FromMilliseconds(4),new List<int>{0},new List<LedgerEntry>(),0);p.UpdateBatch(r);p.UpdateBatch(r);Assert.Equal(2UL,p.TotalRuns);}
    [Fact] public void UpdateBatchEmptyStillIncrementsRuns(){var p=new ValidationPipeline();p.Register("v",TimeSpan.FromMilliseconds(5));p.UpdateBatch(new(true,new List<ValidationOutcome>(),TimeSpan.Zero,new List<int>{0},new List<LedgerEntry>(),1));Assert.Equal(1UL,p.TotalRuns);Assert.Equal(0UL,p.Stats(0)!.Observations);}
    [Fact] public void RunThenUpdateBatchRoundTripCheck(){var p=new ValidationPipeline();p.Register("fast",TimeSpan.FromMilliseconds(1));p.Register("slow",TimeSpan.FromMilliseconds(100));var r=p.Run(id=>id==0?(true,TimeSpan.FromMilliseconds(2)):(true,TimeSpan.FromMilliseconds(80)));p.UpdateBatch(r);Assert.Equal(1UL,p.TotalRuns);Assert.Equal(1UL,p.Stats(0)!.Observations);Assert.Equal(1UL,p.Stats(1)!.Observations);}
    [Fact] public void ConfidenceWidthAlwaysPositive(){var p=new ValidationPipeline();var id=p.Register("v",TimeSpan.FromMilliseconds(5));Assert.True(p.Stats(id)!.ConfidenceWidth>0);for(int i=0;i<10;i++)p.Update(new(id,true,TimeSpan.FromMilliseconds(5)));Assert.True(p.Stats(id)!.ConfidenceWidth>0);}
    [Fact] public void VarianceKnownBeta11(){var p=new ValidationPipeline();var id=p.Register("v",TimeSpan.FromMilliseconds(5));Assert.InRange(p.Stats(id)!.Variance-1.0/12.0,-1e-10,1e-10);}
    [Fact] public void AlphaBetaAfterMixedOutcomes(){var p=new ValidationPipeline();var id=p.Register("v",TimeSpan.FromMilliseconds(5));for(int i=0;i<5;i++)p.Update(new(id,false,TimeSpan.FromMilliseconds(5)));for(int i=0;i<3;i++)p.Update(new(id,true,TimeSpan.FromMilliseconds(5)));var s=p.Stats(id)!;Assert.InRange(s.Alpha,5.99,6.01);Assert.InRange(s.Beta,3.99,4.01);Assert.InRange(s.FailureProb,0.59,0.61);}
    [Fact] public void WithConfigCustomPrior(){var p=new ValidationPipeline(Cfg(ga:5,gb:10));var id=p.Register("v",TimeSpan.FromMilliseconds(5));Assert.InRange(p.Stats(id)!.FailureProb,1.0/3-0.01,1.0/3+0.01);}
    [Fact] public void WithConfigCustomCMin(){var p=new ValidationPipeline(Cfg(cmin:TimeSpan.FromMilliseconds(10)));var id=p.Register("v",TimeSpan.FromMilliseconds(1));Assert.True(p.Stats(id)!.CostEma>=TimeSpan.FromMilliseconds(10));}
    [Fact] public void RegisterReturnsSequentialIds(){var p=new ValidationPipeline();Assert.Equal(0,p.Register("a",TimeSpan.FromMilliseconds(1)));Assert.Equal(1,p.Register("b",TimeSpan.FromMilliseconds(2)));Assert.Equal(2,p.Register("c",TimeSpan.FromMilliseconds(3)));}
    [Fact] public void LedgerEntryFieldsMatchStats(){var p=new ValidationPipeline();p.Register("v",TimeSpan.FromMilliseconds(10));for(int i=0;i<5;i++)p.Update(new(0,false,TimeSpan.FromMilliseconds(10)));var(_,l)=p.ComputeOrdering();var e=l[0];var s=p.Stats(0)!;Assert.Equal(e.Id,s.Id);Assert.Equal(e.Name,s.Name);Assert.InRange(e.P-s.FailureProb,-1e-10,1e-10);Assert.Equal(e.C,s.CostEma);}
    [Fact] public void LedgerRanksAreContiguous(){var p=new ValidationPipeline();for(int i=0;i<5;i++)p.Register($"v{i}",TimeSpan.FromMilliseconds((i+1)*10));var(_,l)=p.ComputeOrdering();Assert.Equal(new[]{0,1,2,3,4},l.Select(e=>e.Rank).OrderBy(x=>x));}
    [Fact] public void ScoreWithCostAtCMin(){var p=new ValidationPipeline();var id=p.Register("v",TimeSpan.FromTicks(10));Assert.True(p.Stats(id)!.Score(TimeSpan.FromTicks(10))>1.0);}
    [Fact] public void ScoreWithVeryLargeCost(){var p=new ValidationPipeline();var id=p.Register("v",TimeSpan.FromSeconds(1000000));Assert.True(p.Stats(id)!.Score(TimeSpan.FromTicks(10))<1.0);}

    [Fact] public void PipelineConfigDebugFormat(){Assert.Contains("PipelineConfig",PipelineConfig.Default.ToString());}
    [Fact] public void ValidatorStatsDebugFormat(){var p=new ValidationPipeline();p.Register("test_v",TimeSpan.FromMilliseconds(5));Assert.Contains("ValidatorStats",p.Stats(0)!.ToString());}
    [Fact] public void PipelineResultDebugFormat(){var r=new PipelineResult(true,new(),TimeSpan.Zero,new List<int>{0},new(),0);Assert.Contains("PipelineResult",r.ToString());}
    [Fact] public void ValidationOutcomeDebugFormat(){var o=new ValidationOutcome(42,false,TimeSpan.FromMilliseconds(10));Assert.Contains("ValidationOutcome",o.ToString());Assert.Contains("42",o.ToString());}
    [Fact] public void LedgerEntryDebugFormat(){var e=new LedgerEntry(7,"test",0.75,TimeSpan.FromMilliseconds(10),75,0);Assert.Contains("LedgerEntry",e.ToString());}
    [Fact] public void PipelineSummaryDebugFormat(){var s=new PipelineSummary(2,5,new List<int>{1,0},0.015,0.020,0.25,new());Assert.Contains("PipelineSummary",s.ToString());}
    [Fact] public void UpdateDoesNotIncrementTotalRuns(){var p=new ValidationPipeline();p.Register("v",TimeSpan.FromMilliseconds(5));p.Update(new(0,true,TimeSpan.FromMilliseconds(5)));Assert.Equal(0UL,p.TotalRuns);}
    [Fact] public void CostEmaMultipleUpdatesConverge(){var p=new ValidationPipeline(Cfg(gamma:0.5));var id=p.Register("v",TimeSpan.FromMilliseconds(100));for(int i=0;i<50;i++)p.Update(new(id,true,TimeSpan.FromMilliseconds(10)));Assert.InRange(p.Stats(id)!.CostEma.TotalMilliseconds,9.9,10.1);}
    [Fact] public void ValidatorCountAfterMultipleRegisters(){var p=new ValidationPipeline();Assert.Equal(0,p.ValidatorCount);p.Register("a",TimeSpan.FromMilliseconds(5));Assert.Equal(1,p.ValidatorCount);p.Register("b",TimeSpan.FromMilliseconds(10));Assert.Equal(2,p.ValidatorCount);}
}
