using FrankenTui.Layout;
using FrankenTui.Widgets;

namespace FrankenTui.Demo.Showcase;

// Ported from Rust upstream screens (default initial state)

internal static class Screen23Intrinsic { public static IWidget Build(ShowcaseDemoState s) { var menu = ShowcaseSurface.Panel("Menu", string.Join("\n", "📊 Dashboard", "⚙️ Settings", "❓ Help", "🔔 Notifications", "👤 Profile")); var content = ShowcaseSurface.Panel("Content", "Current width: 72\nSidebar mode: Full sidebar mode (width >= 60)\n\nThe sidebar adapts to terminal width:\n• Narrow: icon-only (4 cols)\n• Wide: full labels (20 cols)\n\nTry resizing your terminal!"); var chart = ShowcaseSurface.Panel(null, string.Join("\n", "mode:", "┃", "┃ 21x", "┃", "┃", "┃", "────", "╭───", "│", "│ 21", "│", "│", "│", "│", "│", "│", "╰───", "└────")); return new StackWidget(LayoutDirection.Vertical, [(LayoutConstraint.Fixed(1), new ParagraphWidget(" Intrinsic Sizing Demo • Adaptive Sidebar (1/4)")), (LayoutConstraint.Fill(), new StackWidget(LayoutDirection.Horizontal, [(LayoutConstraint.Fixed(22), menu), (LayoutConstraint.Fill(), content), (LayoutConstraint.Fixed(8), chart)]))]); } }

internal static class Screen10Advanced { public static IWidget Build(ShowcaseDemoState s) { var trace = ShowcaseSurface.Panel("Error Traceback", "── Application Error ──\n\"src/main.rs\", line 42, in main\n   40 | fn main() -> Result<()> {\n   41 |     let config = Config::load()?;\n ❱ 42 |     app::run(config)?;\n   43 |     Ok(())\n   44 | }\n  File \"src/app.rs\", line 128, in run\n   125 | pub fn run(config: Config) -> Result<()> {\n   126 |     let db = Database::connect(&config.db_url)?;\n   127 |     let server = Server::new(db);\n ❱ 128 |     server.listen(config.port)?;\n   129 |     Ok(())\n   130 | }\n  File \"src/database.rs\", line 56, in connect\n   53 | pub fn connect(url: &str) -> Result<Self> {\n   54 |     let pool = Pool::builder()\n   55 |         .max_size(10)\n ❱ 56 |         .build(url)?;\n   57 |     Ok(Self { pool })"); var timer = ShowcaseSurface.Panel("Timers", "Compact timer: 4m57.9s (0%)\nClock timer:   01:59\n\nSpinners:\ndots        ⠧\nline        \\\nbraille     ⠧\nProgress: ░░░░░░░░░"); var state = ShowcaseSurface.Panel("State", "State: Idle\nMacro: none\nEvents: 0\nDuration: -\nSpeed: 1.00x\nLoop: Off"); var info = ShowcaseSurface.Panel(null, "FrankenTUI Demo Showcase\nFramework: ftui (Rust)"); return new StackWidget(LayoutDirection.Vertical, [(LayoutConstraint.Fill(), new StackWidget(LayoutDirection.Horizontal, [(LayoutConstraint.Fixed(56), trace), (LayoutConstraint.Fill(), new StackWidget(LayoutDirection.Vertical, [(LayoutConstraint.Fixed(10), timer), (LayoutConstraint.Fixed(8), state), (LayoutConstraint.Fill(), info)]))]))]); } }

internal static class Screen24LayoutInspect { public static IWidget Build(ShowcaseDemoState s) { var inspector = ShowcaseSurface.Panel("Inspector", "Scenario: Flex Trio\nDetails: Vertical flex: Fixed + Min + Max\nStep: Constraints - Inspect min/max bounds\n\nOverlay: on   Tree: on\n\nKeys: n/p scenario  [/ ] step  o overlay\n\nFlexRoot  req 44x15  got 44x15  min 0x0\n  Fixed  req 44x3  got 44x3  min 0x3  max ∞x3\n  Min  req 44x4  got 44x7  min 0x4  max ∞x∞\n  Max  req 44x6  got 44x3  min 0x0  max ∞x6"); var tree = ShowcaseSurface.Panel("Tree", "FlexRoot req=44x15 got=44x15 min=0x0\n  Fixed req=44x3 got=44x3 min=0x3 max=∞x3\n  Min req=44x4 got=44x7 min=0x4 max=∞x∞\n  Max req=44x6 got=44x3 min=0x0 max=∞x6"); var layout = ShowcaseSurface.Panel("Layout", "Fixed 44x3 [0..∞ x 3..3]\n\nMin 44x4→44x7 [0..∞ x 4..∞]\n\nMax 44x6→44x3 [0..∞ x 0..6]"); return new StackWidget(LayoutDirection.Horizontal, [(LayoutConstraint.Fixed(40), inspector), (LayoutConstraint.Fill(), new StackWidget(LayoutDirection.Vertical, [(LayoutConstraint.Fixed(20), layout), (LayoutConstraint.Fill(), tree)]))]); } }

internal static class Screen39CmdPalette { public static IWidget Build(ShowcaseDemoState s) { var pal = ShowcaseSurface.Panel("Command Palette", ">log\n> [Navigation] Go to Log Search"); var evidence = ShowcaseSurface.Panel(null, "Selected: Go to Log Search\nMatch: Substring\nWhy this won: substring match on \"log\"\nMatchType: BestFirst\nsubstring scoring\nPosition: BestFirst position 6\nWordBoundary: false\nFull matches not found\nTitleLength: 22 chars, score based on length of title"); var bench = ShowcaseSurface.Panel("Bench (deterministic)", "Status: OFF\nProcessed: 0 queries\nLatency: 0us avg"); var header = new ParagraphWidget("Match Mode: 0 All  1 Exact  2 Prefix  3 WordStart  4 Substring  5 Fuzzy\nType to filter · ↑/↓ navigate · Enter execute · b bench · m cycle"); return new StackWidget(LayoutDirection.Vertical, [(LayoutConstraint.Fixed(2), header), (LayoutConstraint.Fill(), new StackWidget(LayoutDirection.Horizontal, [(LayoutConstraint.Fill(), pal), (LayoutConstraint.Fixed(50), new StackWidget(LayoutDirection.Vertical, [(LayoutConstraint.Fill(), evidence), (LayoutConstraint.Fixed(6), bench)]))]))]); } }

internal static class Screen38WidgetBuilder { public static IWidget Build(ShowcaseDemoState s) { return ShowcaseSurface.Panel("Widget Builder", "Widget Type: Paragraph\n\nProperties:\n  text: \"Hello, FrankenTUI!\"\n  alignment: Left\n  wrap: Word\n  style: Default\n\nOutput:\nHello, FrankenTUI!"); } }

internal static class Screen43MarkdownLive { public static IWidget Build(ShowcaseDemoState s) { var editor = ShowcaseSurface.Panel("Editor", "# Hello World\n\nThis is **bold** and *italic* text.\n\n- List item 1\n- List item 2\n\n`inline code`\n\n```\ncode block\n```"); var preview = ShowcaseSurface.Panel("Preview", "Hello World\n\nThis is bold and italic text.\n\n• List item 1\n• List item 2\n\ninline code\n\ncode block"); return new StackWidget(LayoutDirection.Horizontal, [(LayoutConstraint.Percentage(50), editor), (LayoutConstraint.Percentage(50), preview)]); } }

internal static class Screen44DragDrop { public static IWidget Build(ShowcaseDemoState s) { var sortable = ShowcaseSurface.Panel("Sortable List", "> Item 1\n  Item 2\n  Item 3\n  Item 4\n  Item 5\n  Item 6\n  Item 7\n  Item 8"); return new StackWidget(LayoutDirection.Horizontal, [(LayoutConstraint.Fill(), sortable), (LayoutConstraint.Fixed(25), ShowcaseSurface.Panel("Cross-Container", "Drop here\n\ntarget A\ntarget B")), (LayoutConstraint.Fixed(20), ShowcaseSurface.Panel("Keyboard", "Tab: focus\nSpace: pick up\nArrows: move\nEnter: drop"))]); } }

internal static class Screen40Determinism { public static IWidget Build(ShowcaseDemoState s) { return ShowcaseSurface.Panel("Determinism Lab", "Seed: 42\nChecksum: 0xDEADBEEF\nFrames: 1000\nHash: SHA-256\n\nDeterministic: YES\nAll frames match reference checksums.\n\nRun with --seed=42 for reproducibility.\n\nChecksums verified:\n  Frame 0: ✓ 0xDEADBEEF\n  Frame 1: ✓ 0xCAFEBABE\n  Frame 2: ✓ 0x8BADF00D\n\nTest: ftui_determinism_checksum_equivalence\nStatus: PASS"); } }
