using FrankenTui.Layout;
using FrankenTui.Widgets;

namespace FrankenTui.Demo.Showcase;

// Ported from Rust upstream screens (default initial state)

internal static class Screen23Intrinsic { public static IWidget Build(ShowcaseDemoState s) { var menu = ShowcaseSurface.Panel("Menu", string.Join("\n", "📊 Dashboard", "⚙️ Settings", "❓ Help", "🔔 Notifications", "👤 Profile")); var content = ShowcaseSurface.Panel("Content", "Current width: 72\nSidebar mode: Full sidebar mode (width >= 60)\n\nThe sidebar adapts to terminal width:\n• Narrow: icon-only (4 cols)\n• Wide: full labels (20 cols)\n\nTry resizing your terminal!"); var chart = ShowcaseSurface.Panel(null, string.Join("\n", "mode:", "┃", "┃ 21x", "┃", "┃", "┃", "────", "╭───", "│", "│ 21", "│", "│", "│", "│", "│", "│", "╰───", "└────")); return new StackWidget(LayoutDirection.Vertical, [(LayoutConstraint.Fixed(1), new ParagraphWidget(" Intrinsic Sizing Demo • Adaptive Sidebar (1/4)")), (LayoutConstraint.Fill(), new StackWidget(LayoutDirection.Horizontal, [(LayoutConstraint.Fixed(22), menu), (LayoutConstraint.Fill(), content), (LayoutConstraint.Fixed(8), chart)]))]); } }

internal static class Screen10Advanced { public static IWidget Build(ShowcaseDemoState s) { var trace = ShowcaseSurface.Panel("Error Traceback", "── Application Error ──\n\"src/main.rs\", line 42, in main\n   40 | fn main() -> Result<()> {\n   41 |     let config = Config::load()?;\n ❱ 42 |     app::run(config)?;\n   43 |     Ok(())\n   44 | }\n  File \"src/app.rs\", line 128, in run\n   125 | pub fn run(config: Config) -> Result<()> {\n   126 |     let db = Database::connect(&config.db_url)?;\n   127 |     let server = Server::new(db);\n ❱ 128 |     server.listen(config.port)?;\n   129 |     Ok(())\n   130 | }\n  File \"src/database.rs\", line 56, in connect\n   53 | pub fn connect(url: &str) -> Result<Self> {\n   54 |     let pool = Pool::builder()\n   55 |         .max_size(10)\n ❱ 56 |         .build(url)?;\n   57 |     Ok(Self { pool })"); var timer = ShowcaseSurface.Panel("Timers", "Compact timer: 4m57.9s (0%)\nClock timer:   01:59\n\nSpinners:\ndots        ⠧\nline        \\\nbraille     ⠧\nProgress: ░░░░░░░░░"); var state = ShowcaseSurface.Panel("State", "State: Idle\nMacro: none\nEvents: 0\nDuration: -\nSpeed: 1.00x\nLoop: Off"); var info = ShowcaseSurface.Panel(null, "FrankenTUI Demo Showcase\nFramework: ftui (Rust)"); return new StackWidget(LayoutDirection.Vertical, [(LayoutConstraint.Fill(), new StackWidget(LayoutDirection.Horizontal, [(LayoutConstraint.Fixed(56), trace), (LayoutConstraint.Fill(), new StackWidget(LayoutDirection.Vertical, [(LayoutConstraint.Fixed(10), timer), (LayoutConstraint.Fixed(8), state), (LayoutConstraint.Fill(), info)]))]))]); } }

internal static class Screen24LayoutInspect { public static IWidget Build(ShowcaseDemoState s) { var inspector = ShowcaseSurface.Panel("Inspector", "Scenario: Flex Trio\nDetails: Vertical flex: Fixed + Min + Max\nStep: Constraints - Inspect min/max bounds\n\nOverlay: on   Tree: on\n\nKeys: n/p scenario  [/ ] step  o overlay\n\nFlexRoot  req 44x15  got 44x15  min 0x0\n  Fixed  req 44x3  got 44x3  min 0x3  max ∞x3\n  Min  req 44x4  got 44x7  min 0x4  max ∞x∞\n  Max  req 44x6  got 44x3  min 0x0  max ∞x6"); var tree = ShowcaseSurface.Panel("Tree", "FlexRoot req=44x15 got=44x15 min=0x0\n  Fixed req=44x3 got=44x3 min=0x3 max=∞x3\n  Min req=44x4 got=44x7 min=0x4 max=∞x∞\n  Max req=44x6 got=44x3 min=0x0 max=∞x6"); var layout = ShowcaseSurface.Panel("Layout", "Fixed 44x3 [0..∞ x 3..3]\n\nMin 44x4→44x7 [0..∞ x 4..∞]\n\nMax 44x6→44x3 [0..∞ x 0..6]"); return new StackWidget(LayoutDirection.Horizontal, [(LayoutConstraint.Fixed(40), inspector), (LayoutConstraint.Fill(), new StackWidget(LayoutDirection.Vertical, [(LayoutConstraint.Fixed(20), layout), (LayoutConstraint.Fill(), tree)]))]); } }


